[package]
name = "guessing_game"
version = "0.1.0"
authors = ["varunk08 <varunk08@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"